"""empty message

Revision ID: 9f130d5608c9
Revises: 
Create Date: 2026-07-01 22:57:06.941983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f130d5608c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thesis_supervision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scientific_supervisor', sa.String(length=100), nullable=True),
    sa.Column('student', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=400), nullable=False),
    sa.Column('spec_code', sa.String(length=10), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('faculty', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_supervision_scientific_supervisor'), 'thesis_supervision', ['scientific_supervisor'], unique=False)
    op.create_table('thesis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.String(length=255), nullable=False),
    sa.Column('spec_code', sa.String(length=10), nullable=False),
    sa.Column('text_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('error_text', sa.String(length=512), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('last_completed_step', sa.Integer(), nullable=False),
    sa.Column('failed_step', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['thesis_supervision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_file_hash'), 'thesis', ['file_hash'], unique=False)
    op.create_index(op.f('ix_thesis_status'), 'thesis', ['status'], unique=False)
    op.create_table('thesis_direction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=140), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis_keyword_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('keyword_candidate', sa.String(length=255), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('main_theme', sa.String(length=255), nullable=False),
    sa.Column('subject_area', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('relevance', sa.String(length=255), nullable=False),
    sa.Column('object_of_research', sa.String(length=255), nullable=False),
    sa.Column('tools_and_methods', sa.String(length=255), nullable=False),
    sa.Column('main_tasks', sa.String(length=255), nullable=False),
    sa.Column('main_chapters', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thesis_steps')
    op.drop_table('thesis_metadata')
    op.drop_table('thesis_keyword_candidates')
    op.drop_table('thesis_direction')
    op.drop_index(op.f('ix_thesis_status'), table_name='thesis')
    op.drop_index(op.f('ix_thesis_file_hash'), table_name='thesis')
    op.drop_table('thesis')
    op.drop_index(op.f('ix_thesis_supervision_scientific_supervisor'), table_name='thesis_supervision')
    op.drop_table('thesis_supervision')
    # ### end Alembic commands ###
